name: IRCTransport
main: com.bukkit.hef.IRCTransport.IRCTransport
version: 0.1
website: http://github.com/hef/IRCTransport
author: hef
description: >
             IRC Transport Plugin for minecraft chat.
             Forwards all chat messages from minecraft to irc,
             and all irc messages to minecraft players.
commands:
  join:
    description: join a channel
    usage: |
           /<command> <channel>
           Example: /<command> #tutoring
           Example: /<command> #siggame