verbose: false
suppress:
  initial_userlist: false
  initial_topic: false
server:
  address: localhost
  port: 6667
  password:
  ssl: false
  webirc_password:
default:
  prefix:
  suffix:
  channels:
    - channel: '#minecraft'
