verbose: false
suppress:
  initial_userlist: false
  initial_topic: false
server:
  address: localhost
  port: 6667
  password:
  ssl:
    enabled: false
    trust: false
  webirc_password:
  nicksize: 16
default:
  prefix:
  suffix:
  channels:
    - channel: '#minecraft'
autojoin: '#minecraft'
messages:
  chat-irc: '[&e${CHANNEL}&f] &d${NICK}: &f${MESSAGE}'
  quit: '&d${NICK} &fleft'
  private: '&d${NICK}: &f${MESSAGE}'
  part: '&d${NICK} &fleft'
  rename: '&d${OLDNICK} &fis now &d${NEWNICK}'
  kick: '&d${NICK} &ckicked by &d${OP}: &${REASON}'
  join: '&d${NICK} &fjoined &e${CHANNEL}'
  list: 'On [&e${CHANNEL}&f]: &d${LIST}'
  topic: '[&e${CHANNEL}&f] &dTopic: &${TOPIC}'
  action: '* &d${NICK} &a${ACTION}'
translations:
  hit the ground too hard: hit the ground